"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import {
  CheckCircle2,
  Clipboard,
  Download,
  FileText,
  LockKeyhole,
  Printer,
  ShieldAlert,
  Sparkles,
} from "lucide-react";

import { mockCaseAnalysis } from "@/data/mockCaseData";
import { Button } from "@/components/ui/Button";
import SectionHeader from "@/components/ui/SectionHeader";
import Skeleton from "@/components/ui/Skeleton";

export default function ExportSummary() {
  const sectionRef = useRef<HTMLElement | null>(null);

  const [hasGenerated, setHasGenerated] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [hasCopied, setHasCopied] = useState(false);

  const summary = mockCaseAnalysis.exportSummary;

  const exportText = useMemo(() => {
    return [
      "CASEBRIEF AI — MOCK CASE REVIEW SUMMARY",
      "=======================================",
      "",
      `Case: ${mockCaseAnalysis.caseTitle}`,
      `Type: ${mockCaseAnalysis.caseType}`,
      `Jurisdiction: ${mockCaseAnalysis.jurisdiction}`,
      `Court: ${mockCaseAnalysis.court}`,
      `Document: ${mockCaseAnalysis.documentName}`,
      "",
      summary.title,
      "",
      "Overview:",
      summary.overview,
      "",
      "Key Findings:",
      ...summary.keyFindings.map((finding) => `- ${finding}`),
      "",
      "Recommended Review Areas:",
      ...summary.recommendedReviewAreas.map((area) => `- ${area}`),
      "",
      "Disclaimer:",
      summary.disclaimer,
      "",
      "Generated by CaseBrief AI portfolio mockup.",
      "This is not legal advice, legal strategy, or attorney-reviewed work product.",
    ].join("\n");
  }, [summary]);

  useEffect(() => {
    const section = sectionRef.current;

    if (!section) return;

    const prefersReducedMotion = window.matchMedia(
      "(prefers-reduced-motion: reduce)",
    ).matches;

    if (prefersReducedMotion) return;

    gsap.registerPlugin(ScrollTrigger);

    const ctx = gsap.context(() => {
      gsap.from(".export-header-item", {
        y: 28,
        opacity: 0,
        duration: 0.75,
        stagger: 0.12,
        ease: "power3.out",
        scrollTrigger: {
          trigger: section,
          start: "top 78%",
          once: true,
        },
      });

      gsap.from(".export-control-panel", {
        x: -34,
        opacity: 0,
        duration: 0.8,
        ease: "power3.out",
        scrollTrigger: {
          trigger: ".export-layout",
          start: "top 78%",
          once: true,
        },
      });

      gsap.from(".export-preview-panel", {
        x: 34,
        opacity: 0,
        duration: 0.8,
        delay: 0.08,
        ease: "power3.out",
        scrollTrigger: {
          trigger: ".export-layout",
          start: "top 78%",
          once: true,
        },
      });

      gsap.from(".export-action-button", {
        y: 16,
        opacity: 0,
        duration: 0.45,
        stagger: 0.06,
        ease: "power3.out",
        scrollTrigger: {
          trigger: ".export-action-list",
          start: "top 84%",
          once: true,
        },
      });

      gsap.to(".export-lock-pulse", {
        scale: 1.1,
        opacity: 0.7,
        duration: 1.5,
        repeat: -1,
        yoyo: true,
        ease: "sine.inOut",
      });
    }, section);

    return () => ctx.revert();
  }, []);

  useEffect(() => {
    const section = sectionRef.current;

    if (!section || !hasGenerated) return;

    const prefersReducedMotion = window.matchMedia(
      "(prefers-reduced-motion: reduce)",
    ).matches;

    if (prefersReducedMotion) return;

    const ctx = gsap.context(() => {
      const timeline = gsap.timeline({
        defaults: {
          ease: "power3.out",
        },
      });

      timeline
        .fromTo(
          ".export-generated-shell",
          {
            y: 24,
            opacity: 0,
            scale: 0.985,
          },
          {
            y: 0,
            opacity: 1,
            scale: 1,
            duration: 0.6,
          },
        )
        .from(
          ".export-summary-block",
          {
            y: 24,
            opacity: 0,
            duration: 0.55,
            stagger: 0.1,
          },
          "-=0.25",
        )
        .from(
          ".export-finding-row",
          {
            x: 18,
            opacity: 0,
            duration: 0.42,
            stagger: 0.06,
          },
          "-=0.2",
        )
        .from(
          ".export-review-area",
          {
            y: 16,
            opacity: 0,
            duration: 0.42,
            stagger: 0.06,
          },
          "-=0.15",
        );

      gsap.fromTo(
        ".export-success-icon",
        {
          scale: 0.4,
          rotate: -18,
          opacity: 0,
        },
        {
          scale: 1,
          rotate: 0,
          opacity: 1,
          duration: 0.55,
          ease: "back.out(1.8)",
        },
      );
    }, section);

    return () => ctx.revert();
  }, [hasGenerated]);

  const handleGenerate = () => {
    setIsGenerating(true);
    setHasGenerated(false);

    window.setTimeout(() => {
      setIsGenerating(false);
      setHasGenerated(true);
    }, 950);
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(exportText);
      setHasCopied(true);

      window.setTimeout(() => {
        setHasCopied(false);
      }, 1600);
    } catch {
      setHasCopied(false);
    }
  };

  const handleDownload = () => {
    if (!hasGenerated) return;

    const blob = new Blob([exportText], {
      type: "text/plain;charset=utf-8",
    });

    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");

    link.href = url;
    link.download = "casebrief-ai-mock-summary.txt";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    if (!hasGenerated) return;

    window.print();
  };

  return (
    <section
      ref={sectionRef}
      id="export"
      className="px-4 py-16 sm:px-6 md:px-10 md:py-20"
    >
      <div className="mx-auto max-w-7xl">
        <div className="mb-10 grid gap-6 xl:grid-cols-[0.95fr_1.05fr] xl:items-end md:mb-12">
          <SectionHeader
            eyebrow="Export Summary"
            title="Turn the analysis into a clean review packet."
            eyebrowClassName="export-header-item"
            titleClassName="export-header-item"
          />

          <p className="export-header-item leading-8 text-case-muted">
            The export flow simulates how CaseBrief AI would package extracted
            facts, issue flags, missing evidence, and review recommendations
            into a structured summary for human review.
          </p>
        </div>

        <div className="export-layout grid gap-6 xl:grid-cols-[0.75fr_1.25fr] xl:gap-8">
          <aside className="export-control-panel case-card h-fit rounded-[1.5rem] p-4 sm:rounded-[2rem] sm:p-6">
            <div className="export-lock-pulse flex size-12 items-center justify-center rounded-2xl border border-case-border bg-case-gunmetal sm:size-14">
              <FileText className="size-7 text-case-gold" />
            </div>

            <h3 className="mt-5 text-xl font-black sm:mt-6 sm:text-2xl">
              Export Controls
            </h3>

            <p className="mt-4 text-sm leading-7 text-case-muted sm:text-base">
              Generate a mock case review packet from the structured analysis.
              This is designed to demonstrate product UX, not to produce real
              legal work product.
            </p>

            <div className="case-divider my-6" />

            <div className="export-action-list grid gap-3 sm:grid-cols-2 xl:grid-cols-1">
              <Button
                onClick={handleGenerate}
                disabled={isGenerating}
                variant="signal"
                size="md"
                fullWidth
                className="export-action-button"
              >
                <Sparkles
                  className={isGenerating ? "size-5 animate-spin" : "size-5"}
                />
                {isGenerating
                  ? "Generating..."
                  : hasGenerated
                    ? "Regenerate Summary"
                    : "Generate Summary"}
              </Button>

              <Button
                onClick={handleCopy}
                disabled={!hasGenerated || isGenerating}
                variant="redline"
                size="md"
                fullWidth
                className="export-action-button"
              >
                {hasCopied ? (
                  <>
                    <CheckCircle2 className="size-5 text-case-green" />
                    Copied
                  </>
                ) : (
                  <>
                    <Clipboard className="size-5" />
                    Copy Summary
                  </>
                )}
              </Button>

              <Button
                onClick={handleDownload}
                disabled={!hasGenerated || isGenerating}
                variant="redline"
                size="md"
                fullWidth
                className="export-action-button"
              >
                <Download className="size-5" />
                Download Summary
              </Button>

              <Button
                onClick={handlePrint}
                disabled={!hasGenerated || isGenerating}
                variant="redline"
                size="md"
                fullWidth
                className="export-action-button"
              >
                <Printer className="size-5" />
                Print Preview
              </Button>
            </div>

            <div className="mt-5 rounded-3xl border border-case-red/40 bg-case-red/10 p-4 sm:mt-6">
              <div className="flex gap-3">
                <ShieldAlert className="mt-1 size-5 shrink-0 text-case-red-soft" />
                <p className="text-xs leading-6 text-case-muted sm:text-sm">
                  Exported summaries are mock portfolio outputs. They are not
                  legal briefs, legal advice, or attorney-reviewed documents.
                </p>
              </div>
            </div>
          </aside>

          <div className="export-preview-panel case-card rounded-[1.5rem] p-4 sm:rounded-[2rem] sm:p-5">
            <div className="rounded-[1.25rem] border border-case-border bg-black/45 p-4 sm:rounded-[1.5rem] sm:p-5 md:p-7">
              <div className="mb-6 flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between">
                <div>
                  <div className="inline-flex items-center gap-2 rounded-full border border-case-border bg-case-gunmetal/80 px-3 py-1 text-xs font-bold uppercase tracking-[0.2em] text-case-gold">
                    <LockKeyhole className="size-4" />
                    Generated Review Packet
                  </div>

                  <h3 className="mt-5 text-2xl font-black sm:text-3xl">
                    {hasGenerated
                      ? summary.title
                      : "Summary waiting to generate"}
                  </h3>

                  <p className="mt-3 max-w-2xl text-sm leading-7 text-case-muted sm:text-base">
                    {hasGenerated
                      ? "The mock export has been assembled from the analyzed case data."
                      : "Click Generate Summary to simulate the final AI export transition."}
                  </p>
                </div>

                <div
                  className={`flex size-12 shrink-0 items-center justify-center rounded-2xl border sm:size-14 ${
                    hasGenerated
                      ? "border-case-green/40 bg-case-green/10"
                      : "border-case-border bg-case-gunmetal"
                  }`}
                >
                  {hasGenerated ? (
                    <CheckCircle2 className="export-success-icon size-7 text-case-green" />
                  ) : (
                    <FileText className="size-7 text-case-gold" />
                  )}
                </div>
              </div>

              {isGenerating ? (
                <div className="rounded-[1.25rem] border border-case-border bg-case-gunmetal/35 p-5 sm:rounded-[1.5rem] sm:p-8">
                  <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-case-border bg-black/35 px-3 py-2 text-xs font-bold uppercase tracking-[0.2em] text-case-gold">
                    <Sparkles className="size-4 animate-spin" />
                    Assembling Export Packet
                  </div>

                  <div className="space-y-4">
                    <Skeleton className="h-8 w-3/4" />
                    <Skeleton className="h-24 w-full" />

                    <div className="grid gap-3 md:grid-cols-2">
                      <Skeleton className="h-20" />
                      <Skeleton className="h-20" />
                      <Skeleton className="h-20" />
                      <Skeleton className="h-20" />
                    </div>

                    <Skeleton className="h-28 w-full" />
                  </div>
                </div>
              ) : !hasGenerated ? (
                <div className="rounded-[1.25rem] border border-dashed border-case-border bg-case-gunmetal/35 p-5 text-center sm:rounded-[1.5rem] sm:p-8">
                  <Sparkles className="mx-auto size-10 text-case-gold" />
                  <h4 className="mt-4 text-xl font-black sm:text-2xl">
                    Ready to generate export summary.
                  </h4>
                  <p className="mx-auto mt-3 max-w-xl text-sm leading-7 text-case-muted sm:text-base">
                    This final step will reveal a structured case review packet
                    containing overview, findings, review areas, and disclaimer.
                  </p>
                </div>
              ) : (
                <div className="export-generated-shell space-y-6">
                  <article className="export-summary-block rounded-[1.25rem] border border-case-border bg-case-gunmetal/40 p-4 sm:rounded-[1.5rem] sm:p-5">
                    <p className="text-xs font-bold uppercase tracking-[0.24em] text-case-gold">
                      Overview
                    </p>

                    <p className="mt-3 text-sm leading-7 text-case-muted sm:text-base">
                      {summary.overview}
                    </p>
                  </article>

                  <article className="export-summary-block rounded-[1.25rem] border border-case-red/40 bg-case-red/10 p-4 sm:rounded-[1.5rem] sm:p-5">
                    <p className="text-xs font-bold uppercase tracking-[0.24em] text-case-gold">
                      Key Findings
                    </p>

                    <div className="mt-4 space-y-3">
                      {summary.keyFindings.map((finding) => (
                        <div
                          key={finding}
                          className="export-finding-row flex gap-3 rounded-2xl border border-case-border bg-black/35 p-3 sm:p-4"
                        >
                          <CheckCircle2 className="mt-1 size-5 shrink-0 text-case-gold" />
                          <p className="text-xs leading-6 text-case-muted sm:text-sm">
                            {finding}
                          </p>
                        </div>
                      ))}
                    </div>
                  </article>

                  <article className="export-summary-block rounded-[1.5rem] border border-case-border bg-case-gunmetal/40 p-5">
                    <p className="text-xs font-bold uppercase tracking-[0.24em] text-case-gold">
                      Recommended Review Areas
                    </p>

                    <div className="mt-4 grid gap-3 xl:grid-cols-2">
                      {summary.recommendedReviewAreas.map((area) => (
                        <div
                          key={area}
                          className="export-review-area rounded-2xl border border-case-border bg-black/35 p-3 sm:p-4"
                        >
                          <p className="text-xs leading-6 text-case-muted sm:text-sm">
                            {area}
                          </p>
                        </div>
                      ))}
                    </div>
                  </article>

                  <article className="export-summary-block rounded-[1.5rem] border border-case-red/40 bg-case-red/10 p-5">
                    <div className="flex gap-3">
                      <ShieldAlert className="mt-1 size-5 shrink-0 text-case-red-soft" />

                      <div>
                        <p className="text-xs font-bold uppercase tracking-[0.24em] text-case-red-soft">
                          Disclaimer
                        </p>

                        <p className="mt-3 text-xs leading-6 text-case-muted sm:text-sm">
                          {summary.disclaimer}
                        </p>
                      </div>
                    </div>
                  </article>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
